/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cpp_CppFunc */

#ifndef _Included_cpp_CppFunc
#define _Included_cpp_CppFunc
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     cpp_CppFunc
	 * Method:    initWindow
	 * Signature: (IILjava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_cpp_CppFunc_initWindow
	(JNIEnv*, jobject, jint, jint, jstring);

	/*
	 * Class:     cpp_CppFunc
	 * Method:    drawRectangle
	 * Signature: (IIIIIIIF)I
	 */
	JNIEXPORT jint JNICALL Java_cpp_CppFunc_drawRectangle
	(JNIEnv*, jobject, jint, jint, jint, jint, jint, jint, jint, jfloat);

	/*
	 * Class:     cpp_CppFunc
	 * Method:    drawCircular
	 * Signature: (IIIIIIF)I
	 */
	JNIEXPORT jint JNICALL Java_cpp_CppFunc_drawCircular
	(JNIEnv*, jobject, jint, jint, jint, jint, jint, jint, jfloat);

	/*
	 * Class:     cpp_CppFunc
	 * Method:    drawTriangle
	 * Signature: (IIIIIIIIIIIF)I
	 */
	JNIEXPORT jint JNICALL Java_cpp_CppFunc_drawTriangle
	(JNIEnv*, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jfloat);

	/*
	 * Class:     cpp_CppFunc
	 * Method:    drawBegin
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_cpp_CppFunc_drawBegin
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
